version: '2.4'

services:

    postgresql_12:
      container_name: trivia_db_postgresql
      ports:
        - "54333:5432"
      image: postgres:12-alpine
      volumes:
        - /postgres-data:/var/lib/postgresql/data
      env_file: .env
      healthcheck:
        test: "exit 0"
